/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TropheesRouteImport } from './routes/trophees'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MonEspaceRouteImport } from './routes/mon-espace'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as LaRouteRouteImport } from './routes/la-route'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MembreIdRouteImport } from './routes/membre.$id'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'

const TropheesRoute = TropheesRouteImport.update({
  id: '/trophees',
  path: '/trophees',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MonEspaceRoute = MonEspaceRouteImport.update({
  id: '/mon-espace',
  path: '/mon-espace',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LaRouteRoute = LaRouteRouteImport.update({
  id: '/la-route',
  path: '/la-route',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MembreIdRoute = MembreIdRouteImport.update({
  id: '/membre/$id',
  path: '/membre/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/feed': typeof FeedRoute
  '/la-route': typeof LaRouteRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/mon-espace': typeof MonEspaceRoute
  '/onboarding': typeof OnboardingRoute
  '/trophees': typeof TropheesRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/membre/$id': typeof MembreIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/feed': typeof FeedRoute
  '/la-route': typeof LaRouteRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/mon-espace': typeof MonEspaceRoute
  '/onboarding': typeof OnboardingRoute
  '/trophees': typeof TropheesRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/membre/$id': typeof MembreIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/feed': typeof FeedRoute
  '/la-route': typeof LaRouteRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/mon-espace': typeof MonEspaceRoute
  '/onboarding': typeof OnboardingRoute
  '/trophees': typeof TropheesRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/membre/$id': typeof MembreIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/feed'
    | '/la-route'
    | '/leaderboard'
    | '/login'
    | '/mon-espace'
    | '/onboarding'
    | '/trophees'
    | '/auth/callback'
    | '/membre/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/feed'
    | '/la-route'
    | '/leaderboard'
    | '/login'
    | '/mon-espace'
    | '/onboarding'
    | '/trophees'
    | '/auth/callback'
    | '/membre/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/feed'
    | '/la-route'
    | '/leaderboard'
    | '/login'
    | '/mon-espace'
    | '/onboarding'
    | '/trophees'
    | '/auth/callback'
    | '/membre/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  FeedRoute: typeof FeedRoute
  LaRouteRoute: typeof LaRouteRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LoginRoute: typeof LoginRoute
  MonEspaceRoute: typeof MonEspaceRoute
  OnboardingRoute: typeof OnboardingRoute
  TropheesRoute: typeof TropheesRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  MembreIdRoute: typeof MembreIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trophees': {
      id: '/trophees'
      path: '/trophees'
      fullPath: '/trophees'
      preLoaderRoute: typeof TropheesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mon-espace': {
      id: '/mon-espace'
      path: '/mon-espace'
      fullPath: '/mon-espace'
      preLoaderRoute: typeof MonEspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/la-route': {
      id: '/la-route'
      path: '/la-route'
      fullPath: '/la-route'
      preLoaderRoute: typeof LaRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membre/$id': {
      id: '/membre/$id'
      path: '/membre/$id'
      fullPath: '/membre/$id'
      preLoaderRoute: typeof MembreIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  FeedRoute: FeedRoute,
  LaRouteRoute: LaRouteRoute,
  LeaderboardRoute: LeaderboardRoute,
  LoginRoute: LoginRoute,
  MonEspaceRoute: MonEspaceRoute,
  OnboardingRoute: OnboardingRoute,
  TropheesRoute: TropheesRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  MembreIdRoute: MembreIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
